export const SOCKET_EVENTS = {
  START_LISTENING: 'start-listening',
  STOP_LISTENING: 'stop-listening',
  PROCESS_CODING_TASK: 'process-coding-task',
  UPDATE_CONFIG: 'update-config',
  TOGGLE_WINDOW: 'toggle-window',
  STATE_CHANGE: 'state-change',
  TRANSCRIPT_CHUNK: 'transcript-chunk',
  TRANSCRIPT: 'transcript',
  AI_RESPONSE_START: 'ai-response-start',
  AI_RESPONSE_CHUNK: 'ai-response-chunk',
  AI_RESPONSE_DONE: 'ai-response-done',
  AI_RESPONSE: 'ai-response',
  ERROR: 'error',
  CONFIG_UPDATED: 'config-updated',
  MODEL_SWITCHED: 'model-switched',
  HOTKEY_PRESSED: 'hotkey-pressed',
  CODING_HOTKEY_PRESSED: 'coding-hotkey-pressed',
  CONNECT: 'connect',
  DISCONNECT: 'disconnect'
} as const;
